config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #会員側のルーティング設定

  scope module: :public do
    resources :customers do
      collection do
        get 'unsubscribe'
        get "check"
        patch 'withdrawal'
      end
    end
    resources :cart_items do
      collection do
        delete 'all_destroy'
      end
    end
    resources :orders do
      collection do
        get 'thanx'
        get 'confirmation'
        post 'confirmation'
      end
    end
    resources :items, only: [:index, :show]
    resources :shipping_addresses
    root to: "homes#top"
    get '/home/about' => 'homes#about', as: 'about'

    get '/search', to: 'searches#search'
  end

  #管理者側のルーティング設定
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update]
    resources :order_details, only: [:update]
    resources :items, except: [:destry]
    resources :item_genres, only: [:index, :edit, :update, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.add_tax_price * quantity
  end

  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :orders
   has_many :cart_items
   has_many :shipping_addresses, dependent: :destroy

   def active_for_authentication?
    super && (is_deleted == false)
   end
  
   def last_and_first_name
    self.last_name + " " + self.first_name
   end
  
   has_many :orders
   has_many :shipping_addresses, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
	  has_one_attached :item_image
    # attachment :item_image

    has_many :cart_items
    belongs_to :item_genre
    has_many :orders, through: :order_details

    def add_tax_price
    (self.price * 1.1).round
    end

    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true

 def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
 end

  def self.search_for(content, method)
    if method == 'perfect'
      Item.where(name: content)
    elsif method == 'forward'
      Item.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      Item.where('name LIKE ?', '%'+content)
    else
      Item.where('name LIKE ?', '%'+content+'%')
    end
  end

end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord

	has_many :items, dependent: :destroy
	has_many :order_details

  validates :name, presence: { message: 'を選択してください。' }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  enum payment_method: { card: 0, furikomi: 1 }
  enum production_status: { on_payment: 0, paid: 1, under_manufacture: 2, on_shipping: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum order_status: { not_possible: 0, awaiting_manufacture: 1, under_manufacture: 2, finish: 3 }

  def subtotal
    item.add_tax_price * quantity
  end

  def total
    item.add_tax_price * quantity
  end

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  #登録した配送先を、注文情報入力に
  def view_shipping_address
    "〒" + self.post_code + " " + self.address + " " + self.name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def check
    @customer = Customer.find(params[:id])
　end

　def withdrawal
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  end

  private

    def customer_params
      params.require(:customer).permit(:email, :password, :last_name, :first_name, :last_name_kana, :first_name_kana, :phone_number, :post_code, :address, :is_deleted)
    end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

 def new
   @item = Item.new
   @item_genres = ItemGenre.all
 end

 def index
   @item = Item.new
   @items = Item.all.page(params[:page]).per(8)
 end

 def show
   @item = Item.find(params[:id])
 end

 def create
   @item = Item.new(item_params)
    if @item.save
    redirect_to admin_item_path(@item.id)
    else
    render:new
    end
 end

 def edit
   @item = Item.find(params[:id])
   @item_genres = ItemGenre.all
 end

 def update
   @item = Item.find(params[:id])
   @item.update(item_params)
   redirect_to admin_item_path(@item.id)
 end

 def destroy
    @item=Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
 end

 private

 def item_params
 params.require(:item).permit(:item_image, :name, :introduction, :item_genre_id, :price, :is_active)
 end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total = @order_details.inject(0) { |sum, order_detail| sum + order_detail.total }
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.production_status == "paid"
      @order_details = @order.order_details
      @order_details.update(order_status: "awaiting_manufacture")
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:production_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    case resource
    when Admin
      root_path
    when Customer
      customer_path(current_customer.id)
    end
  end

  def after_sign_out_path_for(resource)
      new_admin_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:phone_number,:post_code,:address])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/item_genres_helper.rb
module Admin::ItemGenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_genres_helper.rb
module ItemGenresHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container px-5 px-sm-0 mt-5">
  <div class="row">
    <div class="col-md-12">
      <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
        <%= form_with model: @customer do |f| %>
        <table>
          <tr>
            <td class = "pt-3 pb-3">
              <label for="inputName">氏名</label>
            </td>
            <td>
              <%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"名前"%>
              <%= f.text_field :first_name, autofocus: true, id:"inputName", placeholder:"名前"%>
            </td>
          </tr>
          <tr>
            <td class = "pt-3 pb-3">
              <label for="inputName">フリガナ</label>
            </td>
            <td>
              <%= f.text_field :last_name_kana, autofocus: true, id:"inputName", placeholder:"名前"%>
              <%= f.text_field :first_name_kana, autofocus: true, id:"inputName", placeholder:"名前"%>
            </td>
          </tr>
          <tr>
            <td class = "pt-3 pb-3">
              <label for="inputName">郵便番号</label>
            </td>
            <td>
              <%= f.text_field :post_code, autofocus: true, id:"inputPostCode", placeholder:"郵便番号"%>
            <td>
          </tr>
          <tr>
            <td class = "pt-3 pb-3">
              <label for="inputName",>住所</label>
            </td>
            <td>
              <%= f.text_field :address, :size=>"47", autofocus: true, id:"inputAddress", placeholder:"住所"%>
            </td>
          </tr>
          <tr>
            <td class = "pt-3 pb-3">
              <label for="inputName">電話番号</label>
            </td>
            <td>
              <%= f.text_field :phone_number, autofocus: true, id:"inputPhoneNumber", placeholder:"電話番号"%>
            </td>
          </tr>
          <tr>
            <td class = "pr-5 pt-3 pb-3">
              <label for="inputName">メールアドレス</label>
            </td>
            <td>
              <%= f.text_field :email, :size=>"47", autofocus: true, id:"inputEmail", placeholder:"メールアドレス"%>
            </td>
          <tr>
            <td class = "pt-3 pb-3">
              <label for="inputName">会員ステータス</label>
            </td>
            <td>
               <%= f.radio_button :is_deleted, true %>
               <strong><%= f.label :is_deleted, "退会", class: "cotext-active" %></strong>
               <%= f.radio_button :is_deleted, false %>
               <strong><%= f.label :is_deleted, "有効", class: "text-invalid" %></strong>
            </td>
          </tr>
          <tr>
            <td>
            </td>
            <td>
              <%= f.submit "変更を保存",class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        </table>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container px-5 px-sm-0 mt-5">
  <div class="row">
    <div class="col-md-12">
     <h4>会員一覧</h4>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</tag>
            <th colspan="3"></th>
          </tr>
       </thead>
       <tbody>
         <% @customers.each do |customer| %>
           <tr>
             <td><%= customer.id %></td>
             <td><%= link_to "#{customer.last_name}#{customer.first_name}", admin_customer_path(customer.id) %></td>
             <td><%= customer.email %></td>
             <td>
               <% if customer.is_deleted? %>
               <span class="text-active">退会</span>
               <% else %>
               <span class="text-invalid text-success">有効</span>
               <% end %>
             </td>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h4 class = "mt-5 ml-3">会員詳細</h4>
 <div class="col-5 ml-3">
      <h5>登録情報</h5>
        <table class="table table-borderless">
            <tbody>
                <tr>
                    <td>会員ID</td>
                    <td><%= @customer.id %></td>
                </tr>
                <tr>
                    <td>氏名</td>
                    <td><%= @customer.last_name %><%= @customer.first_name %></td>
                </tr>
                <tr>
                    <td>フリガナ</td>
                    <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
                </tr>
                <tr>
                    <td>郵便番号</td>
                    <td><%= @customer.post_code %></td>
                </tr>
                <tr>
                    <td>住所</td>
                    <td><%= @customer.address %></td>
                </tr>
                <tr>
                    <td>電話番号</td>
                    <td><%= @customer.phone_number %></td>
                </tr>
                <tr>
                    <td>メールアドレス</td>
                    <td><%= @customer.email %></td>
                </tr>
                <tr>
                    <td>会員ステータス</td>
                    <td>
                      <% if @customer.is_deleted? %>
                        <span class="text-active">退会</span>
                      <% else %>
                        <span class="text-invalid text-success">有効</span>
                       <% end %>
                    </td>
                </tr>
            </tbody>
        </table>
  </div>
  <div class = "ml-3">
    <%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-sm btn-success" %>
    <%= link_to '注文履歴一覧を見る', orders_path(@customer), class: "btn btn-sm btn-info" %>
  </div>