config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #会員側のルーティング設定

  scope module: :public do
    resources :customers do
      collection do
        get 'unsubscribe'
        get "check"
        patch 'withdrawal'
      end
    end
    resources :cart_items do
      collection do
        delete 'all_destroy'
      end
    end
    resources :orders do
      collection do
        get 'thanx'
        get 'confirmation'
        post 'confirmation'
      end
    end
    resources :items, only: [:index, :show]
    resources :shipping_addresses
    root to: "homes#top"
    get '/home/about' => 'homes#about', as: 'about'

    get '/search', to: 'searches#search'
  end

  #管理者側のルーティング設定
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update]
    resources :order_details, only: [:update]
    resources :items, except: [:destry]
    resources :item_genres, only: [:index, :edit, :update, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.add_tax_price * quantity
  end

  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :orders
   has_many :cart_items
   has_many :shipping_addresses, dependent: :destroy

   def active_for_authentication?
    super && (is_deleted == false)
   end
  
   def last_and_first_name
    self.last_name + " " + self.first_name
   end
  
   has_many :orders
   has_many :shipping_addresses, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
	  has_one_attached :item_image
    # attachment :item_image

    has_many :cart_items
    belongs_to :item_genre
    has_many :orders, through: :order_details

    def add_tax_price
    (self.price * 1.1).round
    end

    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true

 def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
 end

  def self.search_for(content, method)
    if method == 'perfect'
      Item.where(name: content)
    elsif method == 'forward'
      Item.where('name LIKE ?', content+'%')
    elsif method == 'backward'
      Item.where('name LIKE ?', '%'+content)
    else
      Item.where('name LIKE ?', '%'+content+'%')
    end
  end

end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord

	has_many :items, dependent: :destroy
	has_many :order_details

  validates :name, presence: { message: 'を選択してください。' }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  enum payment_method: { card: 0, furikomi: 1 }
  enum production_status: { on_payment: 0, paid: 1, under_manufacture: 2, on_shipping: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum order_status: { not_possible: 0, awaiting_manufacture: 1, under_manufacture: 2, finish: 3 }

  def subtotal
    item.add_tax_price * quantity
  end

  def total
    item.add_tax_price * quantity
  end

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  #登録した配送先を、注文情報入力に
  def view_shipping_address
    "〒" + self.post_code + " " + self.address + " " + self.name
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

 def new
   @item = Item.new
   @item_genres = ItemGenre.all
 end

 def index
   @item = Item.new
   @items = Item.all.page(params[:page]).per(8)
 end

 def show
   @item = Item.find(params[:id])
 end

 def create
   @item = Item.new(item_params)
    if @item.save
    redirect_to admin_item_path(@item.id)
    else
    render:new
    end
 end

 def edit
   @item = Item.find(params[:id])
   @item_genres = ItemGenre.all
 end

 def update
   @item = Item.find(params[:id])
   @item.update(item_params)
   redirect_to admin_item_path(@item.id)
 end

 def destroy
    @item=Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
 end

 private

 def item_params
 params.require(:item).permit(:item_image, :name, :introduction, :item_genre_id, :price, :is_active)
 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    case resource
    when Admin
      root_path
    when Customer
      customer_path(current_customer.id)
    end
  end

  def after_sign_out_path_for(resource)
      new_admin_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:phone_number,:post_code,:address])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/item_genres_helper.rb
module Admin::ItemGenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_genres_helper.rb
module ItemGenresHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to image_tag("logo.png"), root_path %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li class="nav-item">
                  <%= link_to customer_path(current_customer), class: 'nav-link text-warning' do %>
                    <i class="fas fa-house-user"></i>マイページ
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to items_path, class: 'nav-link text-warning' do %>
                    <i class="fas fa-cheese"></i>商品一覧
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to cart_items_path, class: 'nav-link text-warning' do  %>
                    <i class="fas fa-shopping-cart"></i>カート
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-warning' do %>
                    <i class="fas fa-sign-out-alt"></i>ログアウト
                  </li>
                <%end%>
                <li class="search_form">
                  <%= form_with url: search_path, local: true, method: :get do |f| %>
                    <%= f.text_field :word %>
                    <%= f.select :range, options_for_select([['Item']]) %>
                    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                    <%= f.submit "検索", class: "btn btn-warning" %>
                  <% end %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to admin_items_path, class: 'nav-link text-warning' do  %>
                    <i class="fas fa-cheese"></i>商品一覧

                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to admin_customers_path, class: 'nav-link text-warning' do  %>
                    <i class="fas fa-home"></i>会員一覧
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to admin_orders_path, class: 'nav-link text-warning' do  %>
                    <i class="fas fa-home"></i>注文履歴一覧
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to admin_item_genres_path, class: 'nav-link text-warning' do  %>
                    <i class="fas fa-home"></i>ジャンル一覧
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-warning' do %>
                  <i class="fas fa-sign-out-alt"></i>ログアウト
                </li>
                <%end%>
              <% else %>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-warning' do  %>
                    <i class="fas fa-link"></i>About
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to items_path, class: 'nav-link text-warning' do  %>
                    <i class="fas fa-cheese"></i>商品一覧
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to new_customer_registration_path, class: 'nav-link text-warning' do %>
                    <i class="fas fa-user-plus"></i>新規登録
                  <%end%>
                </li>
                <li class="nav-item">
                  <%= link_to new_customer_session_path, class: 'nav-link text-warning' do %>
                    <i class="fas fa-sign-in-alt"></i>ログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="yield">
    <%= yield %>
    </div>

    <footer class="footer shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div>
            <p class="text-muted">Nagano-cake.inc</p>
          </div>
        </div>
        <div class="container">
          <div class="text-white">
            <h6 class="font-weight-bold"><ガイド><h6>
            <div class="p-1"><%= link_to "ホーム", root_path, class: 'nav-link text-light' %></div>
            <div class="p-1"><%= link_to "アバウト", about_path, class: 'nav-link text-light' %></div>
          </div>
          <div class="text-white">
            <h6 class="font-weight-bold"><コンテンツ></h6>
            <div class="p-1"><%= link_to "マイページ", customers_path, class: 'nav-link text-light' %></div>
            <div class="p-1"><%= link_to "配送先一覧/登録", shipping_addresses_path, class: 'nav-link text-light' %></div>
            <div class="p-1"><%= link_to "注文一覧", orders_path, class: 'nav-link text-light' %></div>
          </div>
          <div></div>
          <div></div>
        </div>

      </nav>
    </footer>

  </body>
</html>