config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  #会員側のルーティング設定

  scope module: :public do
    resources :customers do
      collection do
        get 'unsubscribe'
        get "check"
        patch 'withdrawal'
      end
    end
    resources :cart_items do
      collection do
        delete 'all_destroy'
      end
    end
    resources :orders do
      collection do
        get 'thanx'
        get 'confirmation'
        post 'confirmation'
      end
    end
    resources :items, only: [:index, :show]
    resources :shipping_addresses
    root to: "homes#top"
    get '/home/about' => 'homes#about', as: 'about'

    get '/search', to: 'searches#search'
  end

  #管理者側のルーティング設定
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :index, :update]
    resources :order_details, only: [:update]
    resources :items, except: [:destry]
    resources :item_genres, only: [:index, :edit, :update, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord

	has_many :items, dependent: :destroy
	has_many :order_details

  validates :name, presence: { message: 'を選択してください。' }

end

app/controllers/admin/item_genres_controller.rb
class Admin::ItemGenresController < ApplicationController

  def index
    @item_genre = ItemGenre.new
    @item_genres = ItemGenre.all
  end

  def edit
    @item_genre = ItemGenre.find(params[:id])
  end

  def create
    item_genre = ItemGenre.new(item_genre_params)
    item_genre.save
    redirect_to admin_item_genres_path
  end

  def update
    item_genre = ItemGenre.find(params[:id])
    item_genre.update(item_genre_params)
    redirect_to admin_item_genres_path
  end

  def destroy
    item_genre = ItemGenre.find(params[:id])
    item_genre.destroy
    redirect_to  admin_item_genres_path
  end

  private

  def item_genre_params
    params.require(:item_genre).permit(:name)
  end
end

app/helpers/admin/item_genres_helper.rb
module Admin::ItemGenresHelper
end

app/helpers/item_genres_helper.rb
module ItemGenresHelper
end

app/views/admin/item_genres/edit.html.erb
<h2 class="text-center">ジャンル編集</h2>

 <%= form_with model: @item_genre, url: admin_item_genre_path(@item_genre.id),method: :patch do |f| %>

 <div class="form-group">
  <%= f.label "ジャンル名",class:"form-label" %>
  <%= f.text_field :name,class:"form-control" %>
 </div>

 <%= f.submit '変更を保存', class:"btn btn-success" %>
 <%= link_to "ジャンル一覧に戻る", admin_item_genres_path,class:"btn btn-outline-secondary" %>

 <%= link_to admin_item_genres_path do %>
  <% end %>
  </div>
 <% end %>

app/views/admin/item_genres/index.html.erb
 <h2>ジャンル一覧・追加</h2>

 <%= form_with model: @item_genre,url: admin_item_genres_path do |f| %>
     <%= f.label :name,"ジャンル名" %>
     <%= f.text_field :name %>
 <%= f.submit '新規登録',class:"btn btn-success" %>
 <% end %>

 <table class="table">
   <thead>
     <tr>
     <th>ジャンル</th>
     <th></th>
     </tr>
    </thead>
    <tbody>
 <% @item_genres.each do |item_genre| %>
  <tr>
  <td><%= item_genre.name %></td>
  <td><%= link_to "編集する", edit_admin_item_genre_path(item_genre.id),class:"btn btn-success" %></td>
  </tr>
  <% end %>
 </tbody>
 </table>

app/views/admin/item_genres/update.html.erb
<h1>Admin::ItemGenres#update</h1>
<p>Find me in app/views/admin/item_genres/update.html.erb</p>